[workspace]
resolver = "2"
members = [
    "crates/tg-commons",
    "crates/tg-linker",
    "crates/tg-server",
    "crates/tg-transcriber",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"